/* Shared, input-only DualShock 3 USB driver and explicit DS3CFG serializer. */
struct ds3_usb_context;
#define usb_callback_data_t struct ds3_usb_context
struct ds3_transfer_context;
#define usb_transfer_data_t struct ds3_transfer_context
#include <usbdrvce.h>
#include <fileioc.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "ds3_common.h"

#define CFG_NAME "DS3CFG"
#define CFG_SIZE 88
#define CFG_VERSION 1
#define PROFILE_VID 0x054C
#define PROFILE_PID 0x0268

typedef struct ds3_usb_context { usb_device_t dev; bool enabled,disconnected; } usbctx_t;
typedef struct ds3_transfer_context { volatile bool ready,active; volatile usb_transfer_status_t status; volatile size_t n; } xferctx_t;
typedef struct { bool hid; uint8_t ifnum,epin; uint16_t packet; } layout_t;
static usbctx_t u; static xferctx_t x; static usb_endpoint_t ep; static uint8_t report[64]; static ds3_state_t st;
static void wr16(uint8_t*p,uint16_t v){p[0]=v;p[1]=v>>8;} static uint16_t rd16(const uint8_t*p){return p[0]|((uint16_t)p[1]<<8);}
static void wr32(uint8_t*p,uint32_t v){p[0]=v;p[1]=v>>8;p[2]=v>>16;p[3]=v>>24;} static uint32_t rd32(const uint8_t*p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static uint32_t checksum(const uint8_t *p,size_t n){uint32_t h=2166136261u;while(n--){h^=*p++;h*=16777619u;}return h;}
void ds3_profile_defaults(ds3_profile_t*p){uint8_t i;memset(p,0,sizeof(*p));p->version=CFG_VERSION;p->vid=PROFILE_VID;p->pid=PROFILE_PID;p->lc_x=p->lc_y=p->rc_x=p->rc_y=128;p->lx_min=p->ly_min=p->rx_min=p->ry_min=0;p->lx_max=p->ly_max=p->rx_max=p->ry_max=255;p->dead_l=p->dead_r=8;p->led_mask=2;for(i=0;i<ACT_COUNT;i++)p->action_buttons[i]=0;p->action_buttons[ACT_CONFIRM]=DS3_CROSS;p->action_buttons[ACT_CANCEL]=DS3_CIRCLE;p->action_buttons[ACT_MENU]=DS3_SELECT;p->action_buttons[ACT_PAUSE]=DS3_START;p->action_buttons[ACT_UP]=DS3_UP;p->action_buttons[ACT_RIGHT]=DS3_RIGHT;p->action_buttons[ACT_DOWN]=DS3_DOWN;p->action_buttons[ACT_LEFT]=DS3_LEFT;p->action_buttons[ACT_PAGE_LEFT]=DS3_L1;p->action_buttons[ACT_PAGE_RIGHT]=DS3_R1;p->action_buttons[ACT_PRIMARY]=DS3_SQUARE;p->action_buttons[ACT_SECONDARY]=DS3_TRIANGLE;}
bool ds3_profile_save(const ds3_profile_t*p){uint8_t b[CFG_SIZE],h,i;memset(b,0,sizeof(b));memcpy(b,"D3CF",4);b[4]=CFG_VERSION;b[5]=CFG_SIZE;wr16(b+6,p->vid);wr16(b+8,p->pid);b[10]=p->lc_x;b[11]=p->lc_y;b[12]=p->rc_x;b[13]=p->rc_y;b[14]=p->lx_min;b[15]=p->lx_max;b[16]=p->ly_min;b[17]=p->ly_max;b[18]=p->rx_min;b[19]=p->rx_max;b[20]=p->ry_min;b[21]=p->ry_max;b[22]=p->dead_l;b[23]=p->dead_r;b[24]=p->invert_flags;b[25]=p->led_mask;for(i=0;i<ACT_COUNT;i++)wr32(b+28+i*4,p->action_buttons[i]);wr32(b+84,checksum(b,84));h=ti_Open(CFG_NAME,"w");if(!h)return false;if(ti_Write(b,1,sizeof(b),h)!=sizeof(b)){ti_Close(h);return false;}ti_SetArchiveStatus(1,h);ti_Close(h);return true;}
bool ds3_profile_load(ds3_profile_t*p){uint8_t b[CFG_SIZE],h,i;h=ti_Open(CFG_NAME,"r");if(!h)return false;if(ti_Read(b,1,sizeof(b),h)!=sizeof(b)){ti_Close(h);return false;}ti_Close(h);if(memcmp(b,"D3CF",4)||b[4]!=CFG_VERSION||b[5]!=CFG_SIZE||rd32(b+84)!=checksum(b,84))return false;ds3_profile_defaults(p);p->version=b[4];p->vid=rd16(b+6);p->pid=rd16(b+8);p->lc_x=b[10];p->lc_y=b[11];p->rc_x=b[12];p->rc_y=b[13];p->lx_min=b[14];p->lx_max=b[15];p->ly_min=b[16];p->ly_max=b[17];p->rx_min=b[18];p->rx_max=b[19];p->ry_min=b[20];p->ry_max=b[21];p->dead_l=b[22];p->dead_r=b[23];p->invert_flags=b[24];p->led_mask=b[25];for(i=0;i<ACT_COUNT;i++)p->action_buttons[i]=rd32(b+28+i*4);if(p->vid!=PROFILE_VID||p->pid!=PROFILE_PID||p->dead_l>48||p->dead_r>48)return false;return true;}
uint8_t ds3_apply_axis(uint8_t r,uint8_t c,uint8_t mn,uint8_t mx,uint8_t d,bool inv){int v;if((r>c?r-c:c-r)<=d)v=128;else if(r<c&&c>mn)v=128-((int)(c-r)*128)/(c-mn);else if(r>c&&mx>c)v=128+((int)(r-c)*127)/(mx-c);else v=r;if(v<0)v=0;if(v>255)v=255;if(inv)v=255-v;return v;}
static usb_error_t ev(usb_event_t e,void*d,usbctx_t*s){switch(e){case USB_DEVICE_CONNECTED_EVENT:s->dev=d;s->enabled=false;s->disconnected=false;return usb_ResetDevice(s->dev);case USB_DEVICE_ENABLED_EVENT:s->dev=d;s->enabled=true;break;case USB_DEVICE_DISCONNECTED_EVENT:s->dev=NULL;s->enabled=false;s->disconnected=true;x.active=false;st.connected=false;break;case USB_DEVICE_DISABLED_EVENT:s->enabled=false;break;default:break;}return USB_SUCCESS;}
static usb_error_t cb(usb_endpoint_t e,usb_transfer_status_t q,size_t n,xferctx_t*s){(void)e;s->status=q;s->n=n;s->active=false;s->ready=true;return USB_SUCCESS;}
static bool layout(const uint8_t*d,size_t n,layout_t*o){size_t p=0;uint8_t cur=255;memset(o,0,sizeof(*o));while(p+2<=n){uint8_t z=d[p],t=d[p+1];if(z<2||p+z>n)return false;if(t==USB_INTERFACE_DESCRIPTOR&&z>=9){cur=d[p+2];if(!o->hid&&d[p+5]==USB_HID_CLASS){o->hid=true;o->ifnum=cur;}}else if(t==USB_ENDPOINT_DESCRIPTOR&&z>=7&&o->hid&&cur==o->ifnum){uint8_t a=d[p+2];if((a&128)&&((d[p+3]&3)==USB_INTERRUPT_TRANSFER)){o->epin=a;o->packet=d[p+4]|((uint16_t)d[p+5]<<8);}}p+=z;}return o->hid&&o->epin&&o->packet;}
ds3_result_t ds3_init(void){usb_error_t r;usb_device_descriptor_t dd;size_t got=0,n;static uint8_t cfg[256];layout_t l;usb_control_setup_t en;uint8_t ed[4]={0x42,0x0C,0,0};memset(&u,0,sizeof(u));memset(&x,0,sizeof(x));memset(&st,0,sizeof(st));r=usb_Init(ev,&u,NULL,USB_DEFAULT_INIT_FLAGS);if(r!=USB_SUCCESS)return DS3_USB_INIT_ERROR;while(!u.enabled){r=usb_WaitForInterrupt();if(r!=USB_SUCCESS)return DS3_WAIT_ERROR;}r=usb_GetDeviceDescriptor(u.dev,&dd,sizeof(dd),&got);if(r!=USB_SUCCESS||got<sizeof(dd))return DS3_DESCRIPTOR_ERROR;if(dd.idVendor!=PROFILE_VID||dd.idProduct!=PROFILE_PID)return DS3_WRONG_DEVICE;n=usb_GetConfigurationDescriptorTotalLength(u.dev,0);if(n<9||n>sizeof(cfg))return DS3_CONFIG_ERROR;got=0;r=usb_GetConfigurationDescriptor(u.dev,0,(usb_configuration_descriptor_t*)cfg,n,&got);if(r!=USB_SUCCESS||got!=n||!layout(cfg,n,&l))return DS3_CONFIG_ERROR;r=usb_SetConfiguration(u.dev,(usb_configuration_descriptor_t*)cfg,n);if(r!=USB_SUCCESS)return DS3_CONFIG_ERROR;en.bmRequestType=USB_HOST_TO_DEVICE|USB_CLASS_REQUEST|USB_RECIPIENT_INTERFACE;en.bRequest=9;en.wValue=0x03F4;en.wIndex=l.ifnum;en.wLength=4;r=usb_ControlTransfer(usb_GetDeviceEndpoint(u.dev,0),&en,ed,3,&got);if(r!=USB_SUCCESS)return DS3_ENABLE_ERROR;ep=usb_GetDeviceEndpoint(u.dev,l.epin);if(!ep||l.packet>sizeof(report))return DS3_ENDPOINT_ERROR;x.active=true;r=usb_ScheduleInterruptTransfer(ep,report,l.packet,cb,&x);if(r!=USB_SUCCESS)return DS3_TRANSFER_ERROR;st.connected=true;return DS3_OK;}
void ds3_cleanup(void){usb_Cleanup();memset(&st,0,sizeof(st));}
ds3_result_t ds3_update(void){usb_error_t r;uint32_t b;if(!u.dev||u.disconnected)return DS3_DISCONNECTED;st.fresh=false;r=usb_HandleEvents();if(r!=USB_SUCCESS)return DS3_TRANSFER_ERROR;if(x.ready){x.ready=false;if(x.status!=USB_TRANSFER_COMPLETED||x.n<10||report[0]!=1)return DS3_TRANSFER_ERROR;b=report[2]|((uint32_t)report[3]<<8)|((uint32_t)report[4]<<16);st.pressed=b&~st.buttons;st.released=st.buttons&~b;st.buttons=b;st.raw_lx=st.lx=report[6];st.raw_ly=st.ly=report[7];st.raw_rx=st.rx=report[8];st.raw_ry=st.ry=report[9];st.fresh=true;memset(report,0,sizeof(report));x.active=true;r=usb_ScheduleInterruptTransfer(ep,report,sizeof(report),cb,&x);if(r!=USB_SUCCESS)return DS3_TRANSFER_ERROR;}return DS3_OK;}
const ds3_state_t*ds3_state(void){return &st;}bool ds3_action_down(const ds3_profile_t*p,ds3_action_t a){return a>ACT_NONE&&a<ACT_COUNT&&(st.buttons&p->action_buttons[a]);}bool ds3_action_pressed(const ds3_profile_t*p,ds3_action_t a){return a>ACT_NONE&&a<ACT_COUNT&&(st.pressed&p->action_buttons[a]);}
